-- MySQL Script generated by MySQL Workbench
-- Sat Jun 22 14:31:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sinnombre
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sinnombre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sinnombre` DEFAULT CHARACTER SET utf8 ;
USE `sinnombre` ;

-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `super_admin` TINYINT NOT NULL DEFAULT 0,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` INT(3) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` INT(3) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `country_code` INT(3) NOT NULL,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_departament_countries_idx` (`country_code` ASC) VISIBLE,
  CONSTRAINT `fk_departament_countries`
    FOREIGN KEY (`country_code`)
    REFERENCES `sinnombre`.`tbl_countries` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` INT(3) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `departament_code` INT(3) NOT NULL,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fx_city_departaments_idx` (`departament_code` ASC) VISIBLE,
  CONSTRAINT `fx_city_departaments`
    FOREIGN KEY (`departament_code`)
    REFERENCES `sinnombre`.`tbl_departments` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `logo` TEXT NULL,
  `address` TEXT NOT NULL,
  `city_id` INT NOT NULL,
  `owner_user_id` INT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_tbl_companies_tbl_users1_idx` (`owner_user_id` ASC) VISIBLE,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_tbl_companies_tbl_cities1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_companies_tbl_users1`
    FOREIGN KEY (`owner_user_id`)
    REFERENCES `sinnombre`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_companies_tbl_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `sinnombre`.`tbl_cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `names` VARCHAR(100) NOT NULL,
  `last_names` VARCHAR(100) NOT NULL,
  `avatar` TEXT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `company_uuid` VARCHAR(50) NOT NULL,
  `role_code` VARCHAR(45) NOT NULL,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_tbl_users_tbl_roles1_idx` (`role_code` ASC) VISIBLE,
  INDEX `fk_tbl_users_tbl_companies2_idx` (`company_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_user_roles`
    FOREIGN KEY (`role_code`)
    REFERENCES `sinnombre`.`tbl_roles` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_users_tbl_companies2`
    FOREIGN KEY (`company_uuid`)
    REFERENCES `sinnombre`.`tbl_companies` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_modules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `price` INT(10) NOT NULL,
  `icon` VARCHAR(255) NULL,
  `discount_quarter` INT(3) NULL,
  `discount_semester` INT(3) NULL,
  `discount_year` INT(3) NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `price` INT(10) NOT NULL,
  `discount_quarter` INT(3) NULL,
  `discount_semester` INT(3) NULL,
  `discount_year` INT(3) NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_plan_modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_plan_modules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plan_code` VARCHAR(45) NOT NULL,
  `module_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_plan_modules_idx` (`plan_code` ASC) VISIBLE,
  INDEX `fk_module_plans_idx` (`module_code` ASC) VISIBLE,
  CONSTRAINT `fk_plan_modules`
    FOREIGN KEY (`plan_code`)
    REFERENCES `sinnombre`.`tbl_plans` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_module_plans`
    FOREIGN KEY (`module_code`)
    REFERENCES `sinnombre`.`tbl_modules` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_subscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_uuid` VARCHAR(50) NOT NULL,
  `plan_code` VARCHAR(45) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_subscription_companies_idx` (`company_uuid` ASC) VISIBLE,
  INDEX `fk_tbl_subscriptions_tbl_plans1_idx` (`plan_code` ASC) VISIBLE,
  CONSTRAINT `fk_subscription_companies`
    FOREIGN KEY (`company_uuid`)
    REFERENCES `sinnombre`.`tbl_companies` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_subscriptions_tbl_plans1`
    FOREIGN KEY (`plan_code`)
    REFERENCES `sinnombre`.`tbl_plans` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_suscription_plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_suscription_plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subscriptions_id` INT NOT NULL,
  `module_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_suscription_plans_tbl_subscriptions1_idx` (`subscriptions_id` ASC) VISIBLE,
  INDEX `fk_tbl_suscription_plans_tbl_modules1_idx` (`module_code` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_suscription_plans_tbl_subscriptions1`
    FOREIGN KEY (`subscriptions_id`)
    REFERENCES `sinnombre`.`tbl_subscriptions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_suscription_plans_tbl_modules1`
    FOREIGN KEY (`module_code`)
    REFERENCES `sinnombre`.`tbl_modules` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_parameters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_parameters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `label` VARCHAR(100) NOT NULL,
  `type` VARCHAR(45) NOT NULL COMMENT 'string | number | boolean',
  `default_value` VARCHAR(45) NOT NULL,
  `not_null` TINYINT NOT NULL DEFAULT 0,
  `module_code` VARCHAR(45) NULL,
  `dependence_parameter_code` VARCHAR(45) NULL,
  `dependence_parameter_value` VARCHAR(45) NULL,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_tbl_parameters_tbl_modules1_idx` (`module_code` ASC) VISIBLE,
  INDEX `fk_tbl_parameters_tbl_cities1_idx` (`dependence_parameter_code` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_parameters_tbl_modules1`
    FOREIGN KEY (`module_code`)
    REFERENCES `sinnombre`.`tbl_modules` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_parameters_tbl_cities1`
    FOREIGN KEY (`dependence_parameter_code`)
    REFERENCES `sinnombre`.`tbl_parameters` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_parameter_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_parameter_values` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parameter_code` VARCHAR(45) NOT NULL,
  `company_uuid` VARCHAR(50) NOT NULL,
  `module_code` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_music_configs_tbl_parameters1_idx` (`parameter_code` ASC) VISIBLE,
  INDEX `fk_tbl_music_configs_tbl_companies1_idx` (`company_uuid` ASC) VISIBLE,
  INDEX `fk_tbl_parameter_values_tbl_modules1_idx` (`module_code` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_music_configs_tbl_parameters1`
    FOREIGN KEY (`parameter_code`)
    REFERENCES `sinnombre`.`tbl_parameters` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_music_configs_tbl_companies1`
    FOREIGN KEY (`company_uuid`)
    REFERENCES `sinnombre`.`tbl_companies` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_parameter_values_tbl_modules1`
    FOREIGN KEY (`module_code`)
    REFERENCES `sinnombre`.`tbl_modules` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_artists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NULL,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_albums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `year` INT(4) NULL,
  `image` VARCHAR(45) NULL,
  `artist_uuid` VARCHAR(45) NOT NULL,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_tbl_albums_tbl_artists1_idx` (`artist_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_albums_tbl_artists1`
    FOREIGN KEY (`artist_uuid`)
    REFERENCES `sinnombre`.`tbl_artists` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_songs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `year` INT(4) NULL,
  `duration` INT NULL,
  `visualizations` INT NULL,
  `artist_uuid` VARCHAR(45) NOT NULL,
  `album_uuid` VARCHAR(45) NULL,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_tbl_songs_tbl_artists1_idx` (`artist_uuid` ASC) VISIBLE,
  INDEX `fk_tbl_songs_tbl_albums1_idx` (`album_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_songs_tbl_artists1`
    FOREIGN KEY (`artist_uuid`)
    REFERENCES `sinnombre`.`tbl_artists` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_songs_tbl_albums1`
    FOREIGN KEY (`album_uuid`)
    REFERENCES `sinnombre`.`tbl_albums` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_genders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_genders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_artist_genders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_artist_genders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `artist_uuid` VARCHAR(45) NOT NULL,
  `gender_uuid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_artist_genders_tbl_genders1_idx` (`gender_uuid` ASC) VISIBLE,
  INDEX `fk_tbl_artist_genders_tbl_artists1_idx` (`artist_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_artist_genders_tbl_genders1`
    FOREIGN KEY (`gender_uuid`)
    REFERENCES `sinnombre`.`tbl_genders` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_artist_genders_tbl_artists1`
    FOREIGN KEY (`artist_uuid`)
    REFERENCES `sinnombre`.`tbl_artists` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_song_genders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_song_genders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `song_uuid` VARCHAR(45) NOT NULL,
  `gender_uuid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_song_genders_tbl_songs1_idx` (`song_uuid` ASC) VISIBLE,
  INDEX `fk_tbl_song_genders_tbl_genders1_idx` (`gender_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_song_genders_tbl_songs1`
    FOREIGN KEY (`song_uuid`)
    REFERENCES `sinnombre`.`tbl_songs` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_song_genders_tbl_genders1`
    FOREIGN KEY (`gender_uuid`)
    REFERENCES `sinnombre`.`tbl_genders` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_playlists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NULL,
  `company_uuid` VARCHAR(45) NOT NULL,
  `active_row` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_playlists_tbl_companies1_idx` (`company_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_playlists_tbl_companies1`
    FOREIGN KEY (`company_uuid`)
    REFERENCES `sinnombre`.`tbl_companies` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinnombre`.`tbl_playlist_songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinnombre`.`tbl_playlist_songs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `song_uuid` VARCHAR(45) NOT NULL,
  `playlist_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_playlist_songs_tbl_songs1_idx` (`song_uuid` ASC) VISIBLE,
  INDEX `fk_tbl_playlist_songs_tbl_playlists1_idx` (`playlist_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_playlist_songs_tbl_songs1`
    FOREIGN KEY (`song_uuid`)
    REFERENCES `sinnombre`.`tbl_songs` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_playlist_songs_tbl_playlists1`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `sinnombre`.`tbl_playlists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
